### PR TITLE
Object Cache fixes

### PR DESCRIPTION
**Pull request by cssjoe**
* Fix: Ensure WP Cron events get scheduled when using the Setup Guide wizard and on upgrade
* Fix: Undefined variable when the Object Cache purge debug log is enabled
* Update: Added warnings in the Setup Guide and the General Settings page when using Disk for Database and Object Caches
* Update: Skip Database and Object caches when using WP-CLI

### CODE REVIEW

**Review by jacobd91 — DISMISSED** [review]

**Comment by cssjoe** [comment]
AWS testing passed.

**Review by jacobd91 — DISMISSED** [review]
Approved

**Review by jacobd91 — APPROVED** [review]
Approved

**Review by jacobd91 — APPROVED** [review]
Approved

**Pull request merged**
