### PR TITLE
Add newsletter signup to footer

### PR DESCRIPTION
**Pull request by elanasparkle**
Provides the Newsletter to the footer of the W3 Total Cache plugin. 

image

### CODE REVIEW

**Comment by elanasparkle** [comment]
It wont let me add anything but the ticket is here: 

https://github.com/BoldGrid/w3-total-cache/issues/874

**Comment by bwmarkle** [comment]
General feedback:

image

image

image

----

Thoughts on doing something like this?
image

**Comment by elanasparkle** [comment]
Updated everything should look like this now. 

image

**Review by cssjoe — CHANGES_REQUESTED** [review]
After submitting an email address, the text below is in a small area and pushes the footer up encroaching on the bottom of the page body.  The same thing happens if you click the field and then click elsewhere; the error message increases the height of the footer.

Also, there should be a newline at the end of the file.

**Review by jacobd91 — DISMISSED** [review]
The subscription appears to work and the UI for it is mostly okay. Joe's concern about the error/success message altering the height of the footer isn't as much of a concern for me as if the user scrolls up the page content is fine so ultimately it doesn't affect functionality

**Review by cssjoe — APPROVED** [review]

**Pull request merged**
